{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app-deployment.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app-deployment.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{ .Values.ingress.hosts | toYaml}}
  gateways:
    {{ .Values.ingress.gateways | toYaml }}
  {{- if .Values.ingress.httpOverride }}
  http:
    {{- .Values.ingress.httpOverride | toYaml | nindent 4}}
  {{- else }}
  http:
  - name: 'app'
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "app-deployment.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}
{{- end }}