name: Release Charts

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main


jobs:
  verify:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Find all changed Chart.yaml
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: charts/**/Chart.yaml
      
      - name: Verify Chart.yaml modification
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "::error::You have modified a chart. but didnt change the Chart.yaml"
          exit 1
      
      - name: Comment on PR with Pre-release Instructions
        uses: actions/github-script@v7
        env:
          CHARTS: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          script: |
            // Split the CHARTS string by spaces and join with newlines
            const chartsList = process.env.CHARTS.split(' ').join('\n');

            const commentBody = `
            This PR looks good to me! ✅ However, consider verifying it with a pre-release tag before merging.

            The charts that will get the new tag are:
            \`\`\`
            ${chartsList}
            \`\`\`

            > [!NOTE]  
            > Can't see a chart you edited? Make sure you changed the Chart.yaml.

            ### How to Create a Pre-release Tag:
            To create a pre-release tag, simply comment:

            \`/pre-release <tag-name>\`

            This helps ensure stability before the final release.
            `;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });